services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    devices:
      - /dev/nvidia0:/dev/nvidia0
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama_init
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      '
      echo "waiting for ollama...";
      until ollama list >/dev/null 2>&1; do sleep 1; done;

      echo "Pulling models...";
      ollama pull nomic-embed-large;
      ollama pull bge-m3:latest;

      echo "finished pulling models";
      '
    restart: "no"

volumes:
  ollama_storage:
